### ISSUE TITLE
Object

### ISSUE THREAD

**Issue by zsmn** [MaracatronicsRobotics/Armorial-Suassuna-Legacy#77]
The Object class will be responsible for parsing Ball and Robot's protobuf packages, storing their information and allowing more simplified requests of field elements that were received through the Armorial-Carrero.
_Note: we need to check if this class is really needed or if we can simply bypass it._

- [ ] Create the Object class allowing into the constructor to receive either a Robot or a Ball protobuf class
- [ ] Create methods to get important info about objects (i.e. position, velocity, acceleration)

**Comment by BrenoOR** [comment]
The actual **Utils** contains both **Ball** and **Robot**, and as well contains general methods to eventually _**set**_ this type of info, but has no _**get**_ method.
I recommend a discussion next meeting.
Possibilities:
1. Utils Class holds only a **Object** method instead of both **Ball** and **Robot**, wich sets only the basic info of the Object. And the sets of specific info stays in Objects class, and we implement the _**get**_ methods inside the Object Class or it's children (Ball and Robot).
2. Utils Class holds **Object**, **Ball** and **Robot**, doing the basics. And we implement the _**get**_ methods inside the Object Class, and eventually in it's children.
3. Utils Class holds everyone like in num. 3, but the _**get**_ methods stays only inside the Object Class. (This case we do not implement it's children classes Ball and Robot.
_**Obs.:** The implementation of classes Ball and Robot listed above would have only the job to hold information. (I don't think they could have a use, once that we already have them implemented by protobuf)_
